### ISSUE TITLE
Causes overflow hidden on body, even when acctual modal is not showing

### ISSUE THREAD

**Issue by jb-san** [weahead/react-customizable-modal#4]
https://github.com/weahead/react-customizable-modal/blob/b332d7bebbe74293b5d6c4426c784aec9fb3a00a/src/containers/Modal.tsx#L39

**Comment by michaellopez** [comment]
@jb-san How about this approach?

We pass `isOpen` to `useBodyScrollLock` here https://github.com/weahead/react-customizable-modal/blob/master/src/containers/Modal.tsx#L39 

Then we check that inside `useBodyScrollLock` and only apply the styles when `isOpen` is `true` https://github.com/weahead/react-customizable-modal/blob/master/src/hooks/useBodyScrollLock.ts#L4

Would that be enough / an appropriate way to solve it you think?

Because we can't execute `useBodyScrollLock` conditionally...

**Comment by jb-san** [comment]
I have solved it, just by moving it to a different place, Ill push the updates later today
